### ISSUE TITLE
CSC - Architectures and protocols for remote signature applications version 2.1.0.1

### ISSUE THREAD

**Issue by phin10** [eu-digital-identity-wallet/eudi-doc-standards-and-technical-specifications#29]
### Formal name
CSC - Architectures and protocols for remote signature applications version 2.1.0.1

### Overview
When digital signatures are created within a device, the interfaces and functions are standardized, e.g. the API used by the application program to access the signature creation libraries and the interface to the smart card or similar device (if a device is used) holding the signing key. 
When digital signatures move to the cloud, the functions needed to create a digital signature can be distributed across several service instances, each carrying out one or more steps in the signature creation process. The interfaces between such services are however until now not standardized. 
The Cloud Signature Consortium aims to fill this gap in standardization by defining the architectural design, communication protocols, application programming interfaces, data structures, and technical requirements needed to establish interoperable solutions for cloud-based digital signatures. While these specifications are applicable in a wide variety of use cases with different security requirements, the fulfilment of requirements imposed by the eIDAS Regula on of the EU [i.1] is particularly addressed, supporting the creation of “advanced” or “qualified” electronic signatures and electronic seals in the cloud. 
This document contains technical specifications that are intended for use by applications for creating digital signatures in the cloud and by a variety of applications consuming these services. 
By implementing their services according to these specifications, service providers can ensure that services are applicable as parts of complete digital signature systems in the cloud in a plug and play manner. Existing standards and open specifications are considered by the consortium as far as applicable.

### Work Plan
The EC initiated an engagement process with CSC and continues to follow up the development of this TS.
The EC will supply CSC with feedback to this TS for alignment with the requirements of the Regulation and the ARF. Some gaps have been identified and are discussed with CSC.

### Tasks
- [ ] The EC will follow up with CSC for the continuous development of this TS.
- [ ] The EC will pass this TS through the MSP process.
- [ ] The EC will follow up with ETSI regarding ETSI TS 119 432 - Electronic Signatures and Infrastructures (ESI); Protocols for remote digital signature creation, which references the TS by CSC.

### Updates
**2025-10-02**: The EC expects that the next version 2.2 will be available in mid-October 2025.
2025-08-30: The next version of this TS, following v2.1.0.1, will be available by November 2025.

### Alerts
There are no open alerts.

### References
- https://cloudsignatureconsortium.org/wp-content/uploads/2025/01/csc-api-2.1.0.1.pdf
