### ISSUE TITLE
ETSI (4.2.15) Specification of mechanism allowing embedded disclosure policies

### ISSUE THREAD

**Issue by IshaiO** [eu-digital-identity-wallet/eudi-doc-standards-and-technical-specifications#85]
> [!WARNING]
> This ticket was taken out of the active STS Roadmap. 
The ticket was added a label `wontfix` to record the fact that this original request by the EC will be implemented in  [TS 119 472-3](https://github.com/eu-digital-identity-wallet/eudi-doc-standards-and-technical-specifications/issues/398) - where further follow up will be done.  

### Formal name
ETSI (4.2.15) Specification of mechanism allowing embedded disclosure policies

### Overview
The high-level requirements for the embedded disclosure policy need to be further elaborated, with a focus on defining specific use cases where the policy should be applied and identifying the language to be used for expressing these policies.

### Work Plan
- The EC is working and developing a document that will cover this topic. See the reference below. 
- The EC will follow up with ETSI regarding the development of a technical specification.

### Tasks
- [x] The EC is progressing on this topic and preparing a document. See the reference below.  
- [x] The EC will follow up with ETSI for the development of the technical specification.
- [x] The EC will continue to follow up this requirement in https://github.com/eu-digital-identity-wallet/eudi-doc-standards-and-technical-specifications/issues/398.

### Alerts
There are no open alerts.

### References
1. https://github.com/orgs/eu-digital-identity-wallet/projects/36/views/1?pane=issue&itemId=88859942&issue=eu-digital-identity-wallet%7Ceudi-doc-architecture-and-reference-framework%7C334
2. New ticket to be followed - https://github.com/eu-digital-identity-wallet/eudi-doc-standards-and-technical-specifications/issues/398
